// deno-lint-ignore-file no-console -- a generator whose whole output is its console log

/**
 * Refetch the self-hosted fonts.
 *
 * Run this only when the families change. The output is committed, so a normal build never
 * touches the network, and a Google outage cannot take the site's typography with it.
 *
 * Latin and latin-ext only. Swedish sits inside latin and latin-ext is cheap insurance for
 * names; the Vietnamese, Greek and Cyrillic subsets Google serves are bytes nobody here loads.
 */

const SPEC = "family=Familjen+Grotesk:ital,wght@0,400..700;1,400" +
  "&family=Instrument+Serif:ital@0;1";

/** Ask as a browser would, or Google answers with TrueType instead of woff2. */
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

const KEEP = new Set(["latin", "latin-ext"]);
const DIR = "public/fonts";

interface Face {
  family: string;
  style: string;
  weight: string;
  file: string;
  unicodeRange: string;
}

const css = await (await fetch(
  `https://fonts.googleapis.com/css2?${SPEC}&display=swap`,
  { headers: { "user-agent": UA } },
)).text();

await Deno.mkdir(DIR, { recursive: true });

const faces: Face[] = [];
const fetched = new Map<string, number>();

for (const block of css.matchAll(/\/\* (\S+) \*\/\s*@font-face \{([\s\S]*?)\}/g)) {
  const [, subset, body] = block;
  if (!KEEP.has(subset!)) continue;

  const family = body!.match(/font-family: '([^']+)'/)?.[1];
  const style = body!.match(/font-style: (\S+);/)?.[1];
  const weight = body!.match(/font-weight: ([^;]+);/)?.[1]?.trim();
  const url = body!.match(/url\((\S+?)\)/)?.[1];
  const unicodeRange = body!.match(/unicode-range: ([^;]+);/)?.[1]?.trim();
  if (!family || !style || !weight || !url || !unicodeRange) {
    throw new Error(`could not read a face out of the ${subset} block`);
  }

  const file = `${family.toLowerCase().replaceAll(" ", "-")}-${style}-${
    weight.replaceAll(" ", "")
  }-${subset}.woff2`;

  if (!fetched.has(url)) {
    const bytes = new Uint8Array(await (await fetch(url)).arrayBuffer());
    await Deno.writeFile(`${DIR}/${file}`, bytes);
    fetched.set(url, bytes.length);
    console.log(`  ${file}  ${Math.round(bytes.length / 1024)} KB`);
  }

  faces.push({ family, style, weight, file, unicodeRange });
}

if (faces.length === 0) throw new Error("no faces matched, the CSS shape has changed");

const header = `/*
 * Self-hosted, deliberately.
 *
 * Loading these from Google's CDN sent every visitor's IP to a third party on first paint,
 * which is the one thing this product cannot casually do: the whole promise is that a stranger
 * can say hello without anybody's details travelling. It is also what lets the site run with no
 * cookie banner at all.
 *
 * Latin and latin-ext only. Swedish sits inside latin; latin-ext is cheap insurance for names.
 * The Vietnamese, Greek and Cyrillic subsets Google serves are bytes nobody here would load.
 *
 * Generated by scripts/fonts.ts. Run \`deno task fonts\` if the families ever change.
 */
`;

const rules = faces.map((face) =>
  `@font-face {
  font-family: "${face.family}";
  font-style: ${face.style};
  font-weight: ${face.weight};
  font-display: swap;
  src: url("/fonts/${face.file}") format("woff2");
  unicode-range: ${face.unicodeRange};
}`
).join("\n");

await Deno.writeTextFile("public/fonts.css", `${header}\n${rules}\n`);

const total = [...fetched.values()].reduce((sum, n) => sum + n, 0);
console.log(
  `\n${faces.length} faces, ${fetched.size} files, ${Math.round(total / 1024)} KB total`,
);
